export type VOD = {
  Page: string;
  title: string;
  description: string;
  TagName: string;
  thumbnail: string;
  current_page_url: string;
  ParentPageURL: string;
  DsapceVideoUrl: string;
  page_lastmodifiedby: string;
  Page_PublishedBy: string;
  publishedDate: string;
  lastModifiedDate: string;
  content_type: string;
  author: string;
};

export type PageSettings = {
  Page: string;
  Description: string;
  PageViewer: string;
  PageCaching: string;
  PageMobileFriendly: string;
  SeoTitle: string;
  SeoDescription: string;
  SchedulePublishDateTime: string;
  SeoKeywords: string[];
  SeoBlockIndexing: string;
  SocialOgTitle: string;
  SocialOgDescription: string;
  SocialOgSiteName: string;
  SocialOgType: string;
  SocialOgURL: string;
  SocialOgLocale: string;
  SocialOgImage: string;
  SocialOgTwitterTitle: string;
  SocialOgTwitterDescription: string;
  SocialOgTwitterImage: string;
  SocialOgTwitterURL: string;
  SocialTwitterCardSize: string;
  IsScheduleUnpublish: string;
  ScheduleUnpublishDateTime: string;
  IsSchedulePublish: string;
};

export type VODResponse = {
  data: {
    publish_fetchVodByContent: {
      Page: string;
      Description: string;
      Title: string;
      DsapceVideoUrl: string;
      Thumbnail: string;
      Poster: string;
      ShortDescription: string;
      TagName: string;
      VodVideoId: number[];
      VodAccountId: number[];
      PlayerId: string;
      PublishedDate: string;
      CurrentPageURL: string;
      ParentPageURL: string;
      Tags: string[];
      Page_State: string;
      lastModifiedDate: string;
      Author: string;
      Page_CreatedBy: string;
      Page_LastModifiedBy: string;
      Page_PublishedBy: string;
      IsEdit: boolean;
      IsSoftDelete: boolean;
      SeoEnable: boolean;
      AnalyticsEnable: boolean;
      RobotTxt: boolean;
      SiteMap: boolean;
      Others: null;
      Analytics: null;
      StructureData: string;
      Seo: null;
      DevelopedBy: string;
      DevelopedDate: string;
      creationDate: string;
      PageSettings: PageSettings;
      LatestVods: VOD[];
      UserActionInfo: string;
      StreamingURL: string;
    };
  };
};
